# Generated by Django 5.1.1 on 2024-10-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocoaApp', '0002_remove_parcelle_producteur_id_cooperative_idcoop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producteur',
            name='coop_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
