# Generated by Django 5.1.1 on 2024-10-14 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocoaApp', '0002_alter_producteur_id_producteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='producteur',
            name='autre_cooperative',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='producteur',
            name='cooperative',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='id_producteur',
            field=models.CharField(max_length=500),
        ),
    ]
