# Generated by Django 5.1.1 on 2024-10-14 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocoaApp', '0003_producteur_autre_cooperative_producteur_cooperative_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acheteur',
            name='contact',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='acheteur',
            name='coordonnees_geographiques',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='acheteur',
            name='filiale',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='acheteur',
            name='nom',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='acheteur',
            name='numero_cni',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='acheteur',
            name='numero_oncc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='acheteur',
            name='prenom',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='acheteur',
            name='type_acheteur',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='arrondissement',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='contact_responssable',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='coordonnees_gps',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='departement',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='nom',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='nom_responssable',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='region',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='siege_social',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='type_cooperative',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='village',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='numero_lot',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='type_commercial',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='parcelle',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='parcelle',
            name='numero_titre_foncier',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='parcelle',
            name='url_carte',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='an_enreg',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='genre',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='id_producteur',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='identifiant_fodecc_cicc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='lieu_naissance',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='nom',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='numero_cni',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='numero_telephone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='prenom',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='residence',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='tel_second',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sac',
            name='code_qr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='mot_de_passe',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='nom',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
