# Generated by Django 5.1.1 on 2024-10-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocoaApp', '0003_producteur_coop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producteur',
            name='date_naissance',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
